arduino store: blockMem_C Class Reference
blockMem_C Class Reference
Wrapper for storageBlock_C but working with only 1 block id(eg all the 1wire chips saved info).
#include <store.h>
Public Member Functions
void setId (byte id1)
byte getId ()
void setMemManager (storageBlock_C &o)
byte blockSize ()
byte slotSize ()
mem for block = number of slots * slot size.
byte readByte (byte slot, byte offset)
bool readSlot (byte slot, void *r)
Read a slot of data from storage. e.g. eeprom, flash, SDcard(only eeprom for now)
bool writeByte (byte slot, byte offset, byte value)
bool writeSlot (byte slot, void *r)
void print ()
byte getSlots ()
Private Member Functions
byte blockStart ()
byte blockEnd ()
Private Attributes
byte id
storageBlock_C * memManager
Detailed Description
Wrapper for storageBlock_C but working with only 1 block id(eg all the 1wire chips saved info).
This works with a block of storage consisting of getSlots() slots all of the same size. e.g if we need to store 15 arrays of bytes each 7 bytes long. i.e. Equivelent to: byte arrayOfType[getSlots()=15][7];
Definition at line 73 of file store.h.
Member Function Documentation
blockEnd()
byte blockMem_C::blockEnd () inline private
Definition at line 78 of file store.h.
{ return memManager->blockEnd(id); }
References storageBlock_C::blockEnd(), and memManager.
blockSize()
byte blockMem_C::blockSize () inline
Definition at line 83 of file store.h.
{ return memManager->blockSize(id); }
References storageBlock_C::blockSize(), and memManager.
blockStart()
byte blockMem_C::blockStart () inline private
Definition at line 77 of file store.h.
{ return memManager->blockStart(id); }
References storageBlock_C::blockStart(), and memManager.
getId()
byte blockMem_C::getId () inline
Definition at line 81 of file store.h.
{ return id; }
References id.
getSlots()
byte blockMem_C::getSlots () inline
Definition at line 90 of file store.h.
{ return memManager->getSlots(id);; }
References storageBlock_C::getSlots(), and memManager.
print()
void blockMem_C::print () inline
Definition at line 89 of file store.h.
{ return memManager->print(id); }
References memManager, and storageBlock_C::print().
readByte()
byte blockMem_C::readByte (byte slot, byte offset) inline
Definition at line 85 of file store.h.
{ return memManager->readByte(id, slot, offset); }
References memManager, and storageBlock_C::readByte().
readSlot()
bool blockMem_C::readSlot (byte slot, void * r)
Read a slot of data from storage. e.g. eeprom, flash, SDcard(only eeprom for now)
Parameters
[in] slot The slot to read, mem copy len is = the size of the rec/slot. 0 for first.
[out] r pointer to the memory to copy the slot into. As not using templates need to make sure sizeof(var pointed to by r) >= slot size.
Returns
true true if no problems
false
Definition at line 216 of file store.cpp.
{
    //io_print( ", sizeof(memManager):" ); io_print_n( sizeof( memManager ) );
    //io_print( ", memManager:" ); io_print_n( ( word )( &( *memManager ) ) );
    return memManager->readSlot( id, slot, r );
}
References memManager, and storageBlock_C::readSlot().
setId()
void blockMem_C::setId (byte id1) inline
Definition at line 80 of file store.h.
{ id = id1; }
setMemManager()
void blockMem_C::setMemManager (storageBlock_C & o) inline
Definition at line 82 of file store.h.
{ memManager = &o; }
References memManager.
slotSize()
byte blockMem_C::slotSize () inline
mem for block = number of slots * slot size.
Definition at line 84 of file store.h.
{ return memManager->blocksA[id].size; }
References storageBlock_C::blocksA, id, memManager, and storageBlock_T::size.
writeByte()
bool blockMem_C::writeByte (byte slot, byte offset, byte value) inline
Definition at line 87 of file store.h.
{ return memManager->writeByte(id, slot, offset, value); }
References memManager, and storageBlock_C::writeByte().
writeSlot()
bool blockMem_C::writeSlot (byte slot, void * r) inline
Definition at line 88 of file store.h.
{ return memManager->writeSlot(id, slot, r); }
References memManager, and storageBlock_C::writeSlot().
Member Data Documentation
id
byte blockMem_C::id private
Definition at line 75 of file store.h.
Referenced by getId(), and slotSize().
memManager
storageBlock_C* blockMem_C::memManager private
Definition at line 76 of file store.h.
Referenced by blockEnd(), blockSize(), blockStart(), getSlots(), print(), readByte(), readSlot(), setMemManager(), slotSize(), writeByte(), and writeSlot().
The documentation for this class was generated from the following files:
src/store.h
src/store.cpp