arduino store: storageBlock_C Class Reference
storageBlock_C Class Reference
Blocks of storage. eg. 1 block for 1wire chips and another for room data. each of different lengths with different ids.
#include <store.h>
Public Member Functions
storageBlock_C (byte maxBlocks, storageBlock_T a[], byte startIndex=0)
Pointer to an array used to store each slots details in.
~storageBlock_C ()
void leaveFirst (byte i)
Set the address to start using storage at.
byte addBlock (byte slots, byte recSize)
Add a storage block.
byte blockSize (byte id)
get the storage space size in bytes reserved for the block.
word blockStart (byte blockId)
Get the storage block start address.
word blockEnd (byte id)
get block end index. i.e. the address of last byte used by the block. If block size is 0 there isn't a block end so result will be meaningless.
byte getSlots (byte id)
byte readByte (byte blockId, byte slot, byte offset)
Read a byte of data from a storage block slot.
bool readSlot (byte blockId, byte slot, void *r)
Read a var from permanent storage eg. EEPROM into a var/struct, copys mem of size = to the slot size given when addBlock was called.
bool writeByte (byte blockId, byte slot, byte offset, byte value)
bool writeSlot (byte blockId, byte slot, void *r)
Write a var into permanent storage eg. EEPROM into a var/struct, copys mem of size = to the slot size given when addBlock was called.
void print (byte id)
print info about the storage block to the serial.
void printMemUsage ()
Public Attributes
storageBlock_T * blocksA
No. of elements of blocksA[] used.
Private Attributes
uint16_t nextStartAddr
byte maxBlocks
The address/index to start at for any new block.
byte slotsUsed = 0
The max No. Blocks. The number of array elements in the array used to store the block info in (blocksA).
Detailed Description
Blocks of storage. eg. 1 block for 1wire chips and another for room data. each of different lengths with different ids.
Each blocks info if stored in a extern array.
Parameters
maxBlocks The size of the array.
a a pointer to an extern array used to store the storage info.
startIndex for example with eeprom it could be 15 to stat using the eeprom at address 15;
Definition at line 38 of file store.h.
Constructor & Destructor Documentation
storageBlock_C()
storageBlock_C::storageBlock_C (byte maxBlocks, storageBlock_T a[], byte startIndex = 0)
Pointer to an array used to store each slots details in.
Construct a new storageBlock class object.
Parameters
maxBlocks size of the array a[] in elements(not bytes).
a Pointer to an array to store the storage block info in.
startIndex index to start using the storage media at. eg. with eeprom, use 15 to skip the first 15 bytes of memory.
Definition at line 24 of file store.cpp.
{
    blocksA = a;
    maxBlocks = maxBlocks;
    nextStartAddr = startIndex;
}
References blocksA, maxBlocks, and nextStartAddr.
~storageBlock_C()
storageBlock_C::~storageBlock_C ()
Definition at line 29 of file store.cpp.
{ }
Member Function Documentation
addBlock()
byte storageBlock_C::addBlock (byte slots, byte recSize)
Add a storage block.
No range checking
Parameters
slots number of slots to add
recSize size of each block in bytes.
Returns
byte returns the id of the block.
Definition at line 107 of file store.cpp.
{
    blocksA[ slotsUsed ].start = nextStartAddr;
    blocksA[ slotsUsed ].slots = slots;
    blocksA[ slotsUsed ].size = recSize;
    nextStartAddr += slots * recSize;
    slotsUsed++;
    return slotsUsed - 1;
};
References blocksA, nextStartAddr, storageBlock_T::size, storageBlock_T::slots, slotsUsed, and storageBlock_T::start.
blockEnd()
word storageBlock_C::blockEnd (byte id)
get block end index. i.e. the address of last byte used by the block. If block size is 0 there isn't a block end so result will be meaningless.
Parameters
id Block id, index into blocksA[]
Returns
byte
Definition at line 48 of file store.cpp.
{
    return blocksA[ id ].start + blocksA[ id ].slots * blocksA[ id ].size - 1;
    //mem for block = number of slots * slot size.
    //mem used before block = blocksA[ id ].start - 1.
    // so: i = (blocksA[ id ].start - 1) + blocksA[ id ].slots * blocksA[ id ].size
    // but as start could be 0 so sub 1 at end.
}
References blocksA, storageBlock_T::size, storageBlock_T::slots, and storageBlock_T::start.
Referenced by blockMem_C::blockEnd(), and print().
blockSize()
byte storageBlock_C::blockSize (byte id)
get the storage space size in bytes reserved for the block.
Parameters
id The block id/array index.
Returns
byte block size in bytes.
Definition at line 37 of file store.cpp.
{
    return blocksA[ id ].slots * blocksA[ id ].size; //mem for block = number of slots * slot size.
}
References blocksA, storageBlock_T::size, and storageBlock_T::slots.
Referenced by blockMem_C::blockSize(), and print().
blockStart()
word storageBlock_C::blockStart (byte blockId)
Get the storage block start address.
Parameters
blockId Block id/array index
Returns
word
Definition at line 122 of file store.cpp.
{
    return blocksA[ blockId ].start;
}
References blocksA, and storageBlock_T::start.
Referenced by blockMem_C::blockStart().
getSlots()
byte storageBlock_C::getSlots (byte id) inline
Definition at line 58 of file store.h.
{ return blocksA[id].slots; }
References blocksA, and storageBlock_T::slots.
Referenced by blockMem_C::getSlots().
leaveFirst()
void storageBlock_C::leaveFirst (byte i)
Set the address to start using storage at.
Parameters
i The storage index/ memory address.
Definition at line 61 of file store.cpp.
{
    nextStartAddr = i;// for eeprom the first address is 0 is if i = 15 there would be 15 unused(well by this) bytes.
};
References nextStartAddr.
print()
void storageBlock_C::print (byte id)
print info about the storage block to the serial.
Parameters
id the id(array index) of the block to print the info about.
Definition at line 70 of file store.cpp.
{
    io_print( " storage id: " ); io_print_n( id );
    io_print( ", start address: " ); io_print_n( blocksA[ id ].start );
    io_print( ", end addr: " ); io_print_n( blockEnd( id ) );
    io_print( ", bytes used: " ); io_print_n( blockSize( id ) );
}
References blockEnd(), blocksA, and blockSize().
Referenced by blockMem_C::print().
printMemUsage()
void storageBlock_C::printMemUsage ()
Print storage mem usage.
Definition at line 77 of file store.cpp.
{
#ifdef ATmega328P
    io_println( "MCU = ATmega328P" );
#endif
    io_println( "ATmega328P has 1kByte EEPROM, ATmega1280 and ATmega2560 4KB" );
    //    io_println( "EEPROM use:" );
    io_print( "Storage used:\n\r\tFor vars: " );
    io_print_n( blocksA[ 0 ].start );
    //io_print( "bytes, For switch sender = " );
    //io_println_n( resMemForSwitchCon );
    io_print( "bytes,\n\r\tFor Blocks: " );
    io_println_n( nextStartAddr - blocksA[ 0 ].start );
    io_print( "\tTotal EEPROM memory used in bytes = " );
    io_print_n( nextStartAddr );
    io_print( "bytes, EEPROM memory left bytes = " );
    io_print_n( ( mem_eeprom - ( nextStartAddr ) ) );
    io_print( "bytes, percentage left \u2248 " );//using this  works to
    io_print_n( ( ( mem_eeprom - ( nextStartAddr ) ) * 100ul ) / mem_eeprom ); io_println( "%" );
}
References blocksA, and nextStartAddr.
readByte()
byte storageBlock_C::readByte (byte blockId, byte slot, byte offset)
Read a byte of data from a storage block slot.
Parameters
blockId the index the into the array holding the block info ie. (blocksA[blockId]).
slot The slot number.
offset The byte to read withing the slot starting at 0 for the first.
Returns
byte
Definition at line 134 of file store.cpp.
{
    word i;
    i = blocksA[ blockId ].start + ( slot * blocksA[ blockId ].size );
    return EEPROM.read( i );
}
References blocksA, storageBlock_T::size, and storageBlock_T::start.
Referenced by blockMem_C::readByte().
readSlot()
bool storageBlock_C::readSlot (byte blockId, byte slot, void * r)
Read a var from permanent storage eg. EEPROM into a var/struct, copys mem of size = to the slot size given when addBlock was called.
Parameters
[in] blockId the block of storage, ie. the index to the array
[in] slot The slot to read, mem copy len is = the size of the rec/slot
[out] r pointer to the memory to copy the slot into. As not using templates need to make sure sizeof(var pointed to by r) >= slot size.
Returns
true if no problems
false if slot > num of slots in block.
Definition at line 152 of file store.cpp.
{
    word i, x;
    //io_print( ", id: " ); io_print_n( blockId );// checked to = 1 for 1-wire.
    //io_print( ", slot: " ); io_print_n( slot );
    //io_print( ", &blocksA:" ); io_print_n( ( word )&blocksA );
    //io_print( ", &this:" ); io_print_n( ( word )this );
    //io_print( ", .slots: " ); io_print_n( blocksA[ blockId ].slots );
    //io_print( ", sizeof(r):");io_print_n( sizeof(r) );
    //io_print( ", r:");io_print_n( (word)r );
    //io_print( ", ( byte* )r:"); io_print_n( (word)(( byte* )r) );
    if ( slot > blocksA[ blockId ].slots ) { return false; }
    i = blocksA[ blockId ].start + ( slot * blocksA[ blockId ].size );
    //io_print( ", i(EEPROM addr): " ); io_print_n( i );
    byte* d = ( byte* )r;
    //io_print( ", d:");io_print_n( (word)d );
    for ( x = 0; x < blocksA[ blockId ].size; x++ ) {
        d[ x ] = EEPROM.read( i + x );
        //io_print( "." );
    }
    return true;
}
References blocksA, storageBlock_T::size, and storageBlock_T::start.
Referenced by blockMem_C::readSlot().
writeByte()
bool storageBlock_C::writeByte (byte blockId, byte slot, byte offset, byte value)
Definition at line 196 of file store.cpp.
{
     word i;
     i = blocksA[ blockId ].start + ( slot * blocksA[ blockId ].size ) + offset;
     EEPROM.update( i,  value);
     return true;
}
References blocksA, storageBlock_T::size, and storageBlock_T::start.
Referenced by blockMem_C::writeByte().
writeSlot()
bool storageBlock_C::writeSlot (byte blockId, byte slot, void * r)
Write a var into permanent storage eg. EEPROM into a var/struct, copys mem of size = to the slot size given when addBlock was called.
Parameters
[in] blockId the block of storage, ie. the index to the array
[in] slot The slot to update, mem copy len is = the size of the rec/slot
[out] r pointer to the memory to copy into the slot. As not using templates need to make sure sizeof(var pointed to by r) >= slot size.
Returns
true if no problems
false if slot > num of slots in block.
Definition at line 185 of file store.cpp.
{
    word i, x;
    if ( slot > blocksA[ blockId ].slots ) { return false; }
    i = blocksA[ blockId ].start + ( slot * blocksA[ blockId ].size );
    byte* d = ( byte* )r;
    for ( x = 0; x < blocksA[ blockId ].size; x++ ) {
        EEPROM.update( i + x, d[ x ] );
    }
    return true;
}
References blocksA, storageBlock_T::size, and storageBlock_T::start.
Referenced by blockMem_C::writeSlot().
Member Data Documentation
blocksA
storageBlock_T* storageBlock_C::blocksA
No. of elements of blocksA[] used.
Definition at line 44 of file store.h.
Referenced by addBlock(), blockEnd(), blockSize(), blockStart(), getSlots(), print(), printMemUsage(), readByte(), readSlot(), blockMem_C::slotSize(), storageBlock_C(), writeByte(), and writeSlot().
maxBlocks
byte storageBlock_C::maxBlocks private
The address/index to start at for any new block.
Definition at line 41 of file store.h.
Referenced by storageBlock_C().
nextStartAddr
uint16_t storageBlock_C::nextStartAddr private
Definition at line 40 of file store.h.
Referenced by addBlock(), leaveFirst(), printMemUsage(), and storageBlock_C().
slotsUsed
byte storageBlock_C::slotsUsed = 0 private
The max No. Blocks. The number of array elements in the array used to store the block info in (blocksA).
Definition at line 42 of file store.h.
Referenced by addBlock().
The documentation for this class was generated from the following files:
src/store.h
src/store.cpp